// Invoice status enum
export const INVOICE_STATUS = {
  DRAFT: 'draft',
  SENT: 'sent',
  PENDING: 'pending',
  PAID: 'paid',
  OVERDUE: 'overdue',
  CANCELLED: 'cancelled',
};

// Status display config
export const STATUS_CONFIG = {
  [INVOICE_STATUS.DRAFT]: {
    label: 'Draft',
    color: 'bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300',
    dot: 'bg-zinc-400',
  },
  [INVOICE_STATUS.SENT]: {
    label: 'Sent',
    color: 'bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-300',
    dot: 'bg-blue-400',
  },
  [INVOICE_STATUS.PENDING]: {
    label: 'Pending',
    color: 'bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300',
    dot: 'bg-amber-400',
  },
  [INVOICE_STATUS.PAID]: {
    label: 'Paid',
    color: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300',
    dot: 'bg-emerald-400',
  },
  [INVOICE_STATUS.OVERDUE]: {
    label: 'Overdue',
    color: 'bg-red-50 text-red-700 dark:bg-red-950 dark:text-red-300',
    dot: 'bg-red-400',
  },
  [INVOICE_STATUS.CANCELLED]: {
    label: 'Cancelled',
    color: 'bg-gray-50 text-gray-600 dark:bg-gray-900 dark:text-gray-400',
    dot: 'bg-gray-400',
  },
};

// Currency options
export const CURRENCIES = [
  { value: '₹', label: 'INR', name: 'Indian Rupee' },
  { value: '$', label: 'USD', name: 'US Dollar' },
  { value: '€', label: 'EUR', name: 'Euro' },
  { value: '£', label: 'GBP', name: 'British Pound' },
  { value: '¥', label: 'JPY', name: 'Japanese Yen' },
  { value: 'C$', label: 'CAD', name: 'Canadian Dollar' },
  { value: 'A$', label: 'AUD', name: 'Australian Dollar' },
  { value: 'S$', label: 'SGD', name: 'Singapore Dollar' },
  { value: 'CN¥', label: 'CNY', name: 'Chinese Yuan' },
  { value: '₿', label: 'BTC', name: 'Bitcoin' },
];

// Default invoice item
export const createDefaultItem = () => ({
  id: generateId(),
  name: '',
  description: '',
  quantity: 1,
  price: 0,
  tax: 0,
  productId: null,
  unit: 'pcs',
});

// Default invoice data
export const createDefaultInvoice = (settings = {}) => ({
  id: undefined, // will be auto-generated by Dexie
  invoiceNumber: '',
  status: INVOICE_STATUS.PAID,

  // Company details
  companyName: settings.companyName || '',
  companyEmail: settings.companyEmail || '',
  companyPhone: settings.companyPhone || '',
  companyAddress: settings.companyAddress || '',
  companyLogo: settings.companyLogo || null,
  companyGst: settings.gstNumber || '',

  // Client details (can be linked to a customer)
  customerId: null,
  clientName: '',
  clientEmail: '',
  clientPhone: '',
  clientGst: '',
  billingAddress: '',
  shippingAddress: '',

  // Dates
  issueDate: new Date().toISOString().split('T')[0],
  dueDate: '',

  // Items
  items: [createDefaultItem()],

  // Financial
  currency: settings.defaultCurrency || '₹',
  taxRate: settings.defaultTax || 0,
  discountRate: 0,
  shippingCharges: 0,
  subTotal: 0,
  subtotal: 0,          // lowercase alias — matches Mongoose schema
  taxAmount: 0,
  discountAmount: 0,
  total: 0,
  amount: 0,            // alias kept for backward compat
  grandTotal: 0,        // alias used by PDF templates

  // Footer
  notes: settings.defaultNotes || '',
  terms: settings.defaultTerms || '',

  // Template override (null = use settings default)
  template: null,

  // Metadata
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});

// Generate unique ID
export function generateId() {
  return (+new Date() + Math.floor(Math.random() * 999999)).toString(36);
}

// Generate invoice number
export function generateInvoiceNumber(lastNumber = 0) {
  const next = lastNumber + 1;
  return `INV-${String(next).padStart(4, '0')}`;
}

// Check if a line item is valid (has product or manual name)
export function isValidItem(item) {
  if (!item) return false;
  const hasProduct = !!item.productId;
  const hasName = !!(item.name && item.name.trim());
  return hasProduct || hasName;
}

// Filter out empty/placeholder line items
export function filterValidItems(items) {
  if (!items || !Array.isArray(items)) return [];
  return items.filter(isValidItem);
}

export function normalizeInvoiceItemValue(field, value) {
  if (field === 'quantity') {
    return value === '' || value === null || value === undefined ? '' : String(value);
  }

  if (field === 'price') {
    return value === '' || value === null || value === undefined ? '' : Number(value);
  }

  return value;
}

export function parseInvoiceQuantity(value) {
  if (value === '' || value === null || value === undefined) return 0;

  const parsed = parseInt(value, 10);
  return Number.isNaN(parsed) ? 0 : parsed;
}

export function normalizeInvoiceItemForSave(item) {
  const normalizedQuantity = parseInvoiceQuantity(item?.quantity);
  
  // CRITICAL FIX: Preserve price exactly as-is, only ensure it's a number
  // Never default to 0 unless the value is actually null/undefined/empty string
  let normalizedPrice;
  if (item?.price === null || item?.price === undefined) {
    normalizedPrice = 0;
  } else if (typeof item.price === 'string' && item.price.trim() === '') {
    normalizedPrice = 0;
  } else {
    const parsed = parseFloat(item.price);
    normalizedPrice = isNaN(parsed) ? 0 : parsed;
  }
  
  return {
    ...item,
    quantity: normalizedQuantity,
    price: normalizedPrice,
  };
}

// Prepare invoice for saving — strips empty rows, recalculates totals,
// and always emits every financial field so both client and server schemas
// are satisfied and old invoices that lacked subTotal are healed on save.
export function prepareInvoiceForSave(invoice) {
  const validItems = filterValidItems(invoice.items || []).map(normalizeInvoiceItemForSave);
  const totals = calculateInvoiceTotals(
    validItems,
    invoice.taxRate,
    invoice.discountRate,
    invoice.shippingCharges,
  );
  return {
    ...invoice,
    items: validItems,
    // Canonical camelCase names used throughout the client
    subTotal: totals.subTotal,
    taxAmount: totals.taxAmount,
    discountAmount: totals.discountAmount,
    shippingCharges: parseFloat(invoice.shippingCharges || 0),
    total: totals.total,
    // Aliases kept for backward compatibility with the Mongoose schema
    // (which uses lowercase "subtotal") and older stored documents
    subtotal: totals.subTotal,
    amount: totals.total,
    grandTotal: totals.total,
    clientName: invoice.clientName,
    companyName: invoice.companyName,
  };
}

// Validate invoice has at least one valid line item
export function validateInvoiceItems(invoice) {
  const validItems = filterValidItems(invoice?.items || []);
  if (validItems.length === 0) {
    return { valid: false, message: 'Add at least one line item with a product or item name' };
  }
  return { valid: true, items: validItems };
}

// Validate invoice totals — always recalculate from line items so that
// old invoices missing subTotal, or invoices loaded before a totals update,
// never cause a false validation failure.  Returns the recalculated totals
// so callers can use them directly without a second round-trip.
export function validateInvoiceTotals(invoice) {
  const validItems = filterValidItems(invoice?.items || []);

  // Always recalculate — this is the source of truth.
  const calculatedTotals = calculateInvoiceTotals(
    validItems,
    invoice.taxRate,
    invoice.discountRate,
    invoice.shippingCharges,
  );

  // Resolve stored values: accept both camelCase (subTotal) and lowercase
  // (subtotal) for backward compat with older persisted invoices.
  const storedSubTotal = invoice.subTotal ?? invoice.subtotal ?? null;
  const storedTotal    = invoice.total    ?? invoice.amount   ?? null;

  const tolerance = 0.02; // 2 paise tolerance for float arithmetic

  // If stored values are absent (old invoice) treat them as matching —
  // prepareInvoiceForSave will write the correct values on the next save.
  const subtotalMatch = storedSubTotal === null
    ? true
    : Math.abs(calculatedTotals.subTotal - storedSubTotal) < tolerance;

  const totalMatch = storedTotal === null
    ? true
    : Math.abs(calculatedTotals.total - storedTotal) < tolerance;

  if (!subtotalMatch) {
    console.warn('[INVOICE-VALIDATION] Subtotal mismatch (will be corrected on save)', {
      invoiceNumber: invoice.invoiceNumber,
      calculated: calculatedTotals.subTotal,
      stored: storedSubTotal,
    });
  }
  if (!totalMatch) {
    console.warn('[INVOICE-VALIDATION] Total mismatch (will be corrected on save)', {
      invoiceNumber: invoice.invoiceNumber,
      calculated: calculatedTotals.total,
      stored: storedTotal,
    });
  }

  return {
    // Always valid — mismatches are healed by prepareInvoiceForSave, not blocked.
    valid: true,
    calculatedTotals,
    subtotalMatch,
    totalMatch,
    items: validItems,
  };
}

// Calculate invoice totals
export function calculateInvoiceTotals(items, taxRate, discountRate, shippingCharges = 0) {
  const subTotal = items.reduce(
    (acc, item) => {
      // CRITICAL FIX: Only default to 0 if price is actually null/undefined
      const price = (item.price === null || item.price === undefined) ? 0 : parseFloat(item.price);
      const quantity = parseInvoiceQuantity(item.quantity);
      const itemTotal = price * quantity;
      return acc + itemTotal;
    },
    0
  );

  // CRITICAL FIX: Only default to 0 if rates are actually null/undefined
  const effectiveTaxRate = (taxRate === null || taxRate === undefined) ? 0 : parseFloat(taxRate);
  const effectiveDiscountRate = (discountRate === null || discountRate === undefined) ? 0 : parseFloat(discountRate);
  const effectiveShipping = (shippingCharges === null || shippingCharges === undefined) ? 0 : parseFloat(shippingCharges);

  const taxAmount = subTotal * (effectiveTaxRate / 100);
  const discountAmount = subTotal * (effectiveDiscountRate / 100);
  const total = subTotal - discountAmount + taxAmount + effectiveShipping;

  return {
    subTotal: parseFloat(subTotal.toFixed(2)),
    taxAmount: parseFloat(taxAmount.toFixed(2)),
    discountAmount: parseFloat(discountAmount.toFixed(2)),
    total: parseFloat(total.toFixed(2)),
  };
}

// Format currency amount
export function formatCurrency(amount, currency = '₹') {
  const num = parseFloat(amount || 0);
  return `${currency}${num.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

// Format date
export function formatDate(dateStr) {
  if (!dateStr) return '';
  try {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}

// Check if invoice is overdue (auto-detect)
export function isOverdue(invoice) {
  if (!invoice) return false;
  if (invoice.status === INVOICE_STATUS.PAID) return false;
  if (invoice.status === INVOICE_STATUS.DRAFT) return false;
  if (invoice.status === INVOICE_STATUS.CANCELLED) return false;
  if (!invoice.dueDate) return false;

  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const due = new Date(invoice.dueDate);
  due.setHours(0, 0, 0, 0);
  return due < now;
}

// Get effective status (accounts for overdue auto-detection)
export function getEffectiveStatus(invoice) {
  if (isOverdue(invoice)) return INVOICE_STATUS.OVERDUE;
  return invoice.status;
}
