// Invoice status enum
export const INVOICE_STATUS = {
  DRAFT: 'draft',
  PENDING: 'pending',
  PAID: 'paid',
};

// Status display config
export const STATUS_CONFIG = {
  [INVOICE_STATUS.DRAFT]: {
    label: 'Draft',
    color: 'bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300',
    dot: 'bg-zinc-400',
  },
  [INVOICE_STATUS.PENDING]: {
    label: 'Pending',
    color: 'bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300',
    dot: 'bg-amber-400',
  },
  [INVOICE_STATUS.PAID]: {
    label: 'Paid',
    color: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300',
    dot: 'bg-emerald-400',
  },
};

// Currency options
export const CURRENCIES = [
  { value: '₹', label: 'INR', name: 'Indian Rupee' },
  { value: '$', label: 'USD', name: 'US Dollar' },
  { value: '€', label: 'EUR', name: 'Euro' },
  { value: '£', label: 'GBP', name: 'British Pound' },
  { value: '¥', label: 'JPY', name: 'Japanese Yen' },
  { value: 'C$', label: 'CAD', name: 'Canadian Dollar' },
  { value: 'A$', label: 'AUD', name: 'Australian Dollar' },
  { value: 'S$', label: 'SGD', name: 'Singapore Dollar' },
  { value: 'CN¥', label: 'CNY', name: 'Chinese Yuan' },
  { value: '₿', label: 'BTC', name: 'Bitcoin' },
];

// Default invoice item
export const createDefaultItem = () => ({
  id: generateId(),
  name: '',
  description: '',
  quantity: 1,
  price: 0,
  tax: 0,
});

// Default invoice data
export const createDefaultInvoice = (settings = {}) => ({
  id: undefined, // will be auto-generated by Dexie
  invoiceNumber: '',
  status: INVOICE_STATUS.DRAFT,

  // Company details
  companyName: settings.companyName || '',
  companyEmail: settings.companyEmail || '',
  companyPhone: settings.companyPhone || '',
  companyAddress: settings.companyAddress || '',
  companyLogo: settings.companyLogo || null,

  // Client details
  clientName: '',
  clientEmail: '',
  clientPhone: '',
  billingAddress: '',
  shippingAddress: '',

  // Dates
  issueDate: new Date().toISOString().split('T')[0],
  dueDate: '',

  // Items
  items: [createDefaultItem()],

  // Financial
  currency: settings.defaultCurrency || '₹',
  taxRate: settings.defaultTax || 0,
  discountRate: 0,
  shippingCharges: 0,
  subTotal: 0,
  taxAmount: 0,
  discountAmount: 0,
  total: 0,

  // Footer
  notes: settings.defaultNotes || '',
  terms: settings.defaultTerms || '',

  // Metadata
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});

// Generate unique ID
export function generateId() {
  return (+new Date() + Math.floor(Math.random() * 999999)).toString(36);
}

// Generate invoice number
export function generateInvoiceNumber(lastNumber = 0) {
  const next = lastNumber + 1;
  return `INV-${String(next).padStart(4, '0')}`;
}

// Calculate invoice totals
export function calculateInvoiceTotals(items, taxRate, discountRate, shippingCharges = 0) {
  const subTotal = items.reduce(
    (acc, item) => acc + parseFloat(item.price || 0) * parseInt(item.quantity || 0, 10),
    0
  );

  const taxAmount = subTotal * ((taxRate || 0) / 100);
  const discountAmount = subTotal * ((discountRate || 0) / 100);
  const total = subTotal - discountAmount + taxAmount + parseFloat(shippingCharges || 0);

  return {
    subTotal: parseFloat(subTotal.toFixed(2)),
    taxAmount: parseFloat(taxAmount.toFixed(2)),
    discountAmount: parseFloat(discountAmount.toFixed(2)),
    total: parseFloat(total.toFixed(2)),
  };
}

// Format currency amount
export function formatCurrency(amount, currency = '₹') {
  const num = parseFloat(amount || 0);
  return `${currency}${num.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

// Format date
export function formatDate(dateStr) {
  if (!dateStr) return '';
  try {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}
